---
exclude_paths:
  - "api/**"
  - "application/Espo/Acl/**"
  - "application/Espo/AclPortal/**"
  - "application/Espo/Controllers/**"
  - "application/Espo/Core/**"
  - "application/Espo/Entities/**"
  - "application/Espo/EntryPoints/**"
  - "application/Espo/Hooks/**"
  - "application/Espo/Jobs/**"
  - "application/Espo/Modules/Crm/**"
  - "application/Espo/Notificators/**"
  - "application/Espo/ORM/**"
  - "application/Espo/Repositories/**"
  - "application/Espo/Resources/**"
  - "application/Espo/SelectManagers/**"
  - "application/Espo/Services/**"
  - "client/**"